export const Icons = {
  SolarInfoCircleBold: "/solar_info-circle-bold.svg",
  solar_settingsLinear: "/solar_settings-linear.svg",
  solar_sortVerticalLinear: "/solar_sort-vertical-linear.svg",
  mingcute_minimize: "/mingcute_minimize-line.svg",
  solar_arrowDownLinear: "/solar_arrow-down-linear.svg",
  altArrowLeftLinear: "/alt-arrow-left-linear.svg",
  altArrowRightLinear: "/alt-arrow-right-linear.svg",
  mingcute_add: "/mingcute_add-line.svg",
  usc00: "/usc00full.png",
  Ellipse7: "/Ellipse7.svg",
  Ellipse6: "/Ellipse6.svg",
  Ellipse7Mint: "/Ellipse7-mint.svg",
  chi62Full: "/chi62-full.png",
  solarKeyLinear: "/solar_key-linear.svg",
  discordIcon: "/bxl_discord-alt.svg",
  twitterIcon: "/bxl_twitter.svg",
  image3: "/image3.png",
  image2: "/image2.png",
  iconParkOutlineCheckSmall: "/icon-park-outline_check-small.svg",
  Group: "/Group.svg",
  Vector1: "/Vector (1).svg",
  Vector2: "/Vector (2).svg",
  Vector: "/Vector.svg",
  box: "/box.svg",
  percentage: "/percentage.svg",
  world: "/world.svg",
  graph: "/graph-full.svg",
  graph2: "/graph-full2.svg",
  solar_add_circle_bold: "/solar_add-circle-bold.svg",
  xButton: "/xButton.svg",
  mintInactive: "/blackSidebarIcons/solar_circle-top-down-linear.svg",
  redeemInactive: "/blackSidebarIcons/solar_circle-top-up-linear.svg",
  lockerInactive: "/blackSidebarIcons/solar_key-linear.svg",
  dsosInactive: "/blackSidebarIcons/solar_clipboard-list-linear.svg",
  vestInactive:
    "/blackSidebarIcons/solar_shield-keyhole-minimalistic-linear.svg",
  earnInctive: "/blackSidebarIcons/solar_wad-of-money-linear.svg",
  mintActive: "/whiteSidebarIcons/solar_circle-top-down-bold.svg",
  redeemActive: "/whiteSidebarIcons/solar_circle-top-up-bold.svg",
  lockerActive: "/whiteSidebarIcons/solar_key-linear.svg",
  dsosActive: "/whiteSidebarIcons/solar_clipboard-list-bold.svg",
  vestActive: "/whiteSidebarIcons/solar_shield-keyhole-minimalistic-bold.svg",
  earnActive: "/whiteSidebarIcons/solar_wad-of-money-linear.svg",
};
