export const Images = {
  ship: "/ship.png",
  Isolation_Mode: "/Isolation_Mode.svg",
  Isolation_Mode1: "/Isolation_Mode1.svg",
  Isolation_Mode2: "/Isolation_Mode2.svg",
  chi_anim1: "/chi_anim1.gif",
  dots1: "/dots1_2.svg",
  fullGraphFinal: "/full-graph-final.svg",
  dotsBgSvg: "/dotsBgSvg.svg",
  stabilanLogo: "/logo/stabilan-logo.png",
  stabilanLandingBitcoin: "/stabilan-landing/bitcoinlanding.png",
  stabilanLandingCrypto: "/stabilan-landing/cryptohand.png",
  stabilanObjectnobg: "/stabilan-landing/objectnobg.png",
  fkejh: "/stabilan-landing/fkejh.png",
};
